version: "3"

services:
  php_8:
    build: 
      ./docker/php
    volumes: 
      - "./src:/var/www/html"
    ports:
      - "9000:9000"

  nginx:
    build:
      ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www/html"
    links:
      - php_8

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./docker/mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306

  composer:
    image: composer
    command: composer install
    volumes:
      - "./src:/app"
